export const RECORD_USERINFO = 'RECORD_USERINFO'
export const GET_USERINFO = 'GET_USERINFO'
export const GROUP= 'GROUP'//配置彩种种类（11选5）
export const BET_CONTENT_FLAG= 'BET_CONTENT_FLAG'//是否弹出投注记录
export const SHOW_RIGHT= 'SHOW_RIGHT'//是否弹出投注记录
export const CURRENT_PLAYER= 'CURRENT_PLAYER'//当前玩法树
export const MONEY= 'MONEY'//当前玩法树
export const ZHU= 'ZHU'//注单数
export const CON= 'CON'//投注内容
export const BET_SUCCESS= 'BET_SUCCESS'//投注是否成功
export const BET_GO_SHOW= 'BET_GO_SHOW'//投注确认标识
export const BET_NOT= 'BET_NOT'//取消投注
export const LIST_NAME= 'LIST_NAME'//右上角彩种名字getPastOpens
export const SEASONID2= 'SEASONID2'//当前期号  
export const GET_PAST_OPENS= 'GET_PAST_OPENS'//过去20期开奖结果 
export const LOOK_ALL_UL= 'LOOK_ALL_UL'//是否过去20期开奖结果
export const DMARR= 'DMARR'//胆码数组
export const DMNUM= 'DMNUM'//胆码最大可选数量
export const RESET= 'RESET'//重置游戏相关组件状态
